### ISSUE TITLE
pk4 returns NotFound for all lookups

### ISSUE THREAD

**Issue by gebi** [Debian/pk4#8] opened 2020-08-21 16:24 UTC
hi,

thx for the awesome tool, after some debian upgrades i wanted to use it again (haven't used it in a long time) and now pk4 just prints a lookup error on all package given (re-gen the DB did not help the issue)

```
% pk4 -resolve_only mesa
2020/08/21 17:53:17 lookup("mesa"): key not found in index
% pk4 -resolve_only pk4
2020/08/21 17:54:47 lookup("pk4"): key not found in index
```

but mesa and pk4 are in `sources.index` that's being used
```
% grep -E '(mesa|pk4)' sources.index
mesa    19.3.3-1
mesa    20.1.5-1
mesa-demos      8.4.0-1
pk4     5
Binary file sources.index matches
```

I re-generated the index and i tried it with both pk4 from debian (testing) and with pk4 directly from source (also with `sources.index` generated from both).

```
% go version
go version go1.14.6 linux/amd64
% dpkg -l pk4
ii  pk4            5+b12        amd64        make available the Debian source package producing the specified package
```

i've uploaded the generated db files to http://mgeb.org/share/pk4_db.tar.zst if it helps debugging.

**Comment by stapelberg** [comment] 2020-08-21 17:39
Thanks for flagging this.

I tried reproducing this issue in Docker (I [don’t run Debian anymore](https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/)), but for me, pk4 5+b12 works:
```
% docker run -t -i debian:sid
# echo deb-src http://deb.debian.org/debian sid main >> /etc/apt/sources.list
# apt update
# apt install pk4
# pk4-generate-index
# pk4 -resolve_only pk4
pk4	5
```

**Comment by stapelberg** [comment] 2020-08-23 07:43
When using the index files you provided, I get the same behavior:

```
root@902cfba9cdb5:/var/cache# mkdir pk4
root@902cfba9cdb5:/var/cache# cd pk4
root@902cfba9cdb5:/var/cache/pk4# tar xf /tmp/pk4_db.tar
root@902cfba9cdb5:/var/cache/pk4# pk4 -resolve_only pk4
2020/08/23 07:42:55 lookup("pk4"): key not found in index
```

**Comment by stapelberg** [comment] 2020-08-23 08:22
I had a look at your index file. Its indexBlock contents are:
```
	// <offset>     <len>
	// 24 a7 0b 00  04 00 00 00 // key len 1
	// 28 a7 0b 00  00 00 00 00 // key len 2
	// 28 a7 0b 00  d4 01 00 00 // key len 3
	// fc a8 0b 00  7d 10 00 00
	// …
```

Notably, the second entry (!) has a length of 0 (!) and a duplicate offset.

This explains the behavior: pk4 is locating the wrong part of the index because looking up the index block is going wrong.

I haven’t looked at why the index would be corrupt in this way.
The empty line at the very top of `sources.index` looks related.

**Comment by stapelberg** [comment] 2020-08-23 08:29
@gebi You can reproduce generating this corrupt index, yes?

Could you make the following change to `cmd/pk4-generate-index/sources.go`, run `go install github.com/Debian/pk4/cmd/...`, re-run `pk4-generate-index` and let me know the logs please?

```diff
@@ -66,6 +67,9 @@ func genIndex(bindex []control.BinaryIndex) index.Index {
 			"bin:" + pkg.Package,
 		} {
 			if existing, ok := pk4index[key]; !ok || version.Compare(src.Version, existing.Version) > 0 {
+				if key == "" {
+					log.Printf("empty key for src=%+v", src)
+				}
 				pk4index[key] = src
 			}
 		}
```

**Comment by gebi** [comment] 2020-08-27 23:34
thx for looking into this :)

with your patch applied i get

```
% ./pk4-generate-index -index_dir ../pk4
2020/08/28 00:47:37 empty key for src={Package: Version:}
2020/08/28 00:47:37 empty key for src={Package: Version:}
```

if i increase the verbosity of your patch a bit:
```
@@ -66,6 +67,9 @@ func genIndex(bindex []control.BinaryIndex) index.Index {
                        "bin:" + pkg.Package,
                } {
                        if existing, ok := pk4index[key]; !ok || version.Compare(src.Version, existing.Version) > 0 {
+                               if key == "" {
+                                       log.Printf("empty key for src=%+v pkg=%+v", src, pkg)
+                               }
                                pk4index[key] = src
                        }
                }
@@ -107,6 +111,7 @@ func genSources() error {
        indices := make([]index.Index, len(targets))
        var eg errgroup.Group
        for idx, target := range targets {
+               log.Printf("processing target: id=%d target=%+v", idx, target)
                if target.ShortDesc != "Packages" || strings.HasSuffix(target.Codename, "-debug") {
                        continue
                }
```

i get
```
% ./pk4-generate-index -index_dir ../pk4
...
2020/08/28 01:27:48 processing target: id=28 target={ShortDesc:Packages Filename:/var/lib/dpkg/status Codename: Release: RepoURI: priority:9223372036854775807}
2020/08/28 01:27:48 empty key for src={Package: Version:} pkg={Paragraph:{Values:map[] Order:[]} Package: Source: Version: InstalledSize: Maintainer: Architecture:- MultiArch: Description: Homepage: DescriptionMD5: Tags:[] Section: Priority: Filename: Size: MD5sum: SHA1: SHA256:
DebugBuildIds:[]}
2020/08/28 01:27:48 empty key for src={Package: Version:} pkg={Paragraph:{Values:map[] Order:[]} Package: Source: Version: InstalledSize: Maintainer: Architecture:- MultiArch: Description: Homepage: DescriptionMD5: Tags:[] Section: Priority: Filename: Size: MD5sum: SHA1: SHA256:
DebugBuildIds:[]}
```

thus is suspect the error to be in `/var/lib/dpkg/status` hope this helps http://mgeb.org/share/status.zst

**Comment by stapelberg** [comment] 2020-08-29 08:39
Thanks for the additional debugging!

Unfortunately, as there is concurrency in play, I think your conclusion might be incorrect: the error message is not related to the previous log message, and your `status` file seems fine. When I change the program to call genIndex with your provided status file, I don’t get any errors.

Hence, let’s disable concurrency and try again. This time, the culprit should be listed the way you expected:

```patch
+++ w/cmd/pk4-generate-index/sources.go
@@ -112,15 +116,15 @@ func genSources() error {
                }
 
                idx, target := idx, target // copy
-               eg.Go(func() error {
-                       index, err := getBinaryIndexFile(target.Filename)
-                       if err != nil {
-                               return err
-                       }
+               //eg.Go(func() error {
+               index, err := getBinaryIndexFile(target.Filename)
+               if err != nil {
+                       return err
+               }
 
-                       indices[idx] = genIndex(index)
-                       return nil
-               })
+               indices[idx] = genIndex(index)
+               return nil
+               //})
        }
 
        if err := eg.Wait(); err != nil {
```

**Comment by gebi** [comment] 2020-08-29 11:31
damn... sry! (i grepped for 'go ' but missed the group stuff.

ok, with your patch slightly modified (also commented out the return nil at the end ;)

```
% go build -race
% GORACE="halt_on_error=1" ./pk4-generate-index -index_dir ../pk4
2020/08/29 12:36:29 processing target: id=24 target={ShortDesc:Packages Filename:/var/lib/apt/lists/pkgs.tailscale.com_stable_debian_dists_bullseye_main_binary-amd64_Packages Codename:bullseye Release:bullseye RepoURI:https://pkgs.tailscale.com/stable/debian/ priority:500}
2020/08/29 12:36:29 empty key for src={Package: Version:} pkg={Paragraph:{Values:map[] Order:[]} Package: Source: Version: InstalledSize: Maintainer: Architecture:- MultiArch: Description: Homepage: DescriptionMD5: Tags:[] Section: Priority: Filename: Size: MD5sum: SHA1: SHA256: DebugBuildIds:[]}
2020/08/29 12:36:29 processing target: id=25 target={ShortDesc:Packages Filename:/var/lib/apt/lists/pkgs.tailscale.com_stable_debian_dists_bullseye_main_binary-i386_Packages Codename:bullseye Release:bullseye RepoURI:https://pkgs.tailscale.com/stable/debian/ priority:500}
2020/08/29 12:36:29 empty key for src={Package: Version:} pkg={Paragraph:{Values:map[] Order:[]} Package: Source: Version: InstalledSize: Maintainer: Architecture:- MultiArch: Description: Homepage: DescriptionMD5: Tags:[] Section: Priority: Filename: Size: MD5sum: SHA1: SHA256: DebugBuildIds:[]}
```

The problem seems to be the tailscale repos which contains two empty lines between packages in the file, normal debian tooling seems to ignore them
```
Package: tailscale
Version: 0.100.0~107
Section: net
Priority: extra
Architecture: amd64
Maintainer: Tailscale Inc <info@tailscale.com>
Installed-Size: 25380
Replaces: tailscale-relay
Depends: iptables, iproute2
Conflicts: tailscale-relay
Homepage: https://www.tailscale.com
Description: The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
Filename: pool/tailscale_0.100.0-107_amd64.deb
Size: 13471030
MD5sum: 1862b5dbb3f81294048c16cc0bcf52db
SHA1: 19b943624c9cc0461d06e13544940e2f7aacfd6a
SHA256: 8e87ece1d6b992eb5ad911aa3641af8dceff04bad9476e70cbc97daa7d004e1e


Package: tailscale
Version: 0.100.0~153
```

Just to be sure because of github / formatting (i replaced the sha256 sum with `AAA`)
```
% hexdump -C foo
00000000  53 48 41 32 35 36 3a 20  41 41 41 0a 0a 0a 50 61  |SHA256: AAA...Pa|
00000010  63 6b 61 67 65 3a 20 74  61 69 6c 73 63 61 6c 65  |ckage: tailscale|
00000020  0a                                                |.|
```

Files in question
```
https://pkgs.tailscale.com/stable/debian/dists/bullseye/main/binary-amd64/Packages.gz
```

**Closed as completed** 2020-08-30 09:21 UTC
Labels: bug

**Comment by stapelberg** [comment] 2020-08-30 09:27
Thanks for the additional debugging!

I have let the tailscale folks known at https://twitter.com/zekjur/status/1299988313097592832

Additionally, commit https://github.com/paultag/go-debian/commit/c1c425c225dd6cc8c9c4bc887f285796ed081fdb fixes the issue in the underlying `pault.ag/go/debian` module.

I have also declared a Go module in pk4, so that you can easily build a working version.

**Comment by danderson** [comment] 2020-08-30 17:45
Fixed in Tailscale's package server - although it's good to also make the parser robust against this, since the Debian repository format spec doesn't specify strict rules for whitespace - only that a Packages file contains "multiple paragraphs".

**Comment by stapelberg** [comment] 2020-08-30 17:49
Thanks very much for the quick fix!

The parser was already made more robust in commit https://github.com/paultag/go-debian/commit/c1c425c225dd6cc8c9c4bc887f285796ed081fdb :)
